# Generated by Django 3.2.13 on 2022-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='verified_as',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Service Personnel', 'Service Personnel')], max_length=30, null=True, verbose_name='Verify as '),
        ),
    ]
