# Generated by Django 3.2.13 on 2022-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_userverification_verified_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='is_payment_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
