# Generated by Django 4.0.3 on 2022-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=70, verbose_name='Your Name')),
                ('sender_mail', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Your Phone Number')),
                ('message', models.TextField(verbose_name='Your Message')),
            ],
        ),
    ]
