# Generated by Django 4.0.3 on 2022-05-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('residential_address', models.TextField(max_length=500, null=True)),
                ('permanent_address', models.TextField(max_length=500, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('state_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
