# Generated by Django 3.2.13 on 2022-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220602_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_as',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Service Personnel', 'Service Personnel')], max_length=50, null=True, verbose_name='Register as'),
        ),
    ]
