# Generated by Django 4.0.3 on 2022-05-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Provide more details like number of rooms')),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='accommodation_pics')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('lga', models.CharField(max_length=64, null=True, verbose_name='Local Government Area')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_type', to='accommodation.accommodationtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='accommodation.state')),
            ],
        ),
    ]
