# Generated by Django 3.2.13 on 2022-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_alter_accommodationdemand_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationpost',
            name='lga',
            field=models.CharField(max_length=64, null=True, verbose_name='Local Government Area/Town/City'),
        ),
    ]
