# Generated by Django 4.0.3 on 2022-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_landpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landpost',
            name='lga',
            field=models.CharField(max_length=64, null=True, verbose_name='LGA / Town / City'),
        ),
        migrations.AlterField(
            model_name='landpost',
            name='location',
            field=models.CharField(help_text='Give a detailed location', max_length=100),
        ),
        migrations.AlterField(
            model_name='landpost',
            name='size',
            field=models.CharField(help_text='How many plots, acres or hectares?', max_length=64),
        ),
    ]
