# Generated by Django 4.0.3 on 2022-05-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_landpost_lga_alter_landpost_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField()),
            ],
        ),
    ]
