# Generated by Django 3.2.13 on 2022-06-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_alter_landdemand_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landpost',
            name='picture',
        ),
    ]
