# Generated by Django 4.0.3 on 2022-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpost',
            name='description',
            field=models.CharField(help_text='Type of Building e.g Hotel, Duplex, Bungalow; and any other information about the building', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingpost',
            name='lga',
            field=models.CharField(max_length=64, null=True, verbose_name='City/Town/Local Government Area'),
        ),
        migrations.AlterField(
            model_name='buildingpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='building_pics'),
        ),
    ]
