# Generated by Django 4.0.3 on 2022-05-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_buildingtype_alter_buildingpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpost',
            name='lga',
            field=models.CharField(max_length=64, null=True, verbose_name='City/Town/LGA'),
        ),
    ]
